version: '3.9'

services:
  backend:
    image: credcars-backend:latest
    build: .
    container_name: credcars-backend
    ports:
      - '3000:3000'
    env_file:
      - .env
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3000/health']
      interval: 10s
      timeout: 5s
      retries: 3
