name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - dev   

jobs:
  deploy:
    name: Deploy App to AWS Elastic Beanstalk
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Zip project for EB
        run: |
          zip -r app.zip . -x ".git/*" "node_modules/*" "test/*"

      - name: Install EB CLI
        run: pip install --upgrade awsebcli

      - name: Configure AWS CLI
        run: aws configure set region ${{ secrets.AWS_REGION }}

      - name: Upload archive to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          aws s3 cp app.zip s3://elasticbeanstalk-$AWS_REGION-211289421537/app-${GITHUB_RUN_NUMBER}.zip

      - name: Deploy to Elastic Beanstalk
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          EB_APP_NAME: ${{ secrets.EB_APP_NAME }}
          EB_ENV_NAME: ${{ secrets.EB_ENV_NAME }}
        run: |
          eb init $EB_APP_NAME --platform node.js-20 --region $AWS_REGION
          eb use $EB_ENV_NAME
          eb deploy --version "app-${GITHUB_RUN_NUMBER}"
