name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    name: Deploy App to AWS Elastic Beanstalk
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # 3. Install dependencies
      - name: Install dependencies
        run: npm ci

      # 4. Build NestJS project
      - name: Build project
        run: npm run build

      # 5. Prepare deployment package
      - name: Prepare deployment package
        run: |
          zip -r app.zip \
            package.json package-lock.json dist/ Procfile .ebextensions/ -x "*.git*" "node_modules/*"

      - name: Verify dist folder
        run: ls -R dist

      # 6. Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # 7. Upload artifact to S3
      - name: Upload artifact to S3
        run: |
          aws s3 cp app.zip s3://elasticbeanstalk-${{ secrets.AWS_REGION }}-${{ secrets.AWS_ACCOUNT_ID }}/app-${{ github.run_number }}.zip

      # 8. Install EB CLI
      - name: Install EB CLI
        run: pip install --upgrade awsebcli

      # 9. Deploy to Elastic Beanstalk
      - name: Deploy to Elastic Beanstalk
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          EB_APP_NAME: ${{ secrets.EB_APP_NAME }}
          EB_ENV_NAME: ${{ secrets.EB_ENV_NAME }}
        run: |
          # Initialize EB if needed
          eb init $EB_APP_NAME --platform node.js-20 --region $AWS_REGION --verbose

          # Use the environment
          eb use $EB_ENV_NAME

          # Deploy with a unique label; automatically creates application version
          eb deploy --staged --label app-${{ github.run_number }} --verbose
